collection: amend gh action

diff --git a/.github/workflows/ansible_software_availability.yml b/.github/workflows/ansible_software_availability.yml
--- a/.github/workflows/ansible_software_availability.yml
+++ b/.github/workflows/ansible_software_availability.yml
@@ -1,6 +1,7 @@
 ---
 
 # This GitHub Action requires the repository to have GitHub Action 'Read and write permissions' under Settings -> Action -> General -> Workflow permissions.
+# Amend GitHub Action 'Artifact and log retention' to 60 days to avoid error 'You are running out of disk space. The runner will stop working when the machine runs out of disk space.'
 
 name: SAP Software Availability Tests
 
@@ -41,6 +42,7 @@ jobs:
           sap_user_id: ${{ secrets.SAP_USER_ID }}
           sap_user_id_password: ${{ secrets.SAP_USER_ID_PASSWORD }}
         run: |
+          if ! which python > /dev/null; then echo 'Python binary not available' && exit 1 ; fi
           export ANSIBLE_COLLECTIONS_PATH="$PWD/ansible_collections"
           cd "./gh_repo/"
           # Extract from softwarecenter_search_list_.* until first empty line, then remove yaml formatting and sort for unique
@@ -72,7 +74,7 @@ jobs:
             echo ""
             cd ./ansible_collections/community/sap_launchpad/plugins
             touch python_module_fuzzy_call_script.py
-            echo '#!/usr/bin/env python3' >> python_module_fuzzy_call_script.py
+            echo '#!/usr/bin/env python' >> python_module_fuzzy_call_script.py
             echo 'import sys' >> python_module_fuzzy_call_script.py
             echo 'input_search_file=sys.argv[1]' >> python_module_fuzzy_call_script.py
             echo 'input_search_file_name_and_version_only=sys.argv[2]' >> python_module_fuzzy_call_script.py
@@ -121,10 +123,13 @@ jobs:
             echo "        list_imdb_lcapps.sort(reverse=True)" >> python_module_fuzzy_call_script.py
             echo "        print(list_imdb_lcapps[0])" >> python_module_fuzzy_call_script.py
             echo "    elif any('IMDB_SERVER' in sublist['Title'] for sublist in query_result):" >> python_module_fuzzy_call_script.py
+            echo "        list_imdb_server = []" >> python_module_fuzzy_call_script.py
             echo "        for sublist in query_result:" >> python_module_fuzzy_call_script.py
             echo "            input_imdb_server = input_search_file_name_and_version_only[:-1]" >> python_module_fuzzy_call_script.py
             echo "            if sublist['Title'].startswith(input_imdb_server):" >> python_module_fuzzy_call_script.py
-            echo "                print(sublist['Title'])" >> python_module_fuzzy_call_script.py
+            echo "                list_imdb_server.append(sublist['Title'])" >> python_module_fuzzy_call_script.py
+            echo "        list_imdb_server.sort(reverse=True)" >> python_module_fuzzy_call_script.py
+            echo "        print(list_imdb_server[0])" >> python_module_fuzzy_call_script.py
             echo "    elif any('SAPWEBDISP' in sublist['Title'] for sublist in query_result):" >> python_module_fuzzy_call_script.py
             echo "        # As SAP WebDisp file name numbering does not use preceeding 0's, manually filter out v7 which is older than v69:" >> python_module_fuzzy_call_script.py
             echo "        input_webdisp = input_search_file_name_and_version_only[:-2]" >> python_module_fuzzy_call_script.py
